"""empty message

Revision ID: 315ece5cc8dc
Revises: 40ec5233c2c4
Create Date: 2019-05-04 15:38:17.838000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315ece5cc8dc'
down_revision = '40ec5233c2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qrcode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.LargeBinary(length=2048), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qrcode')
    # ### end Alembic commands ###
