"""empty message

Revision ID: 70dae4076c9c
Revises: 315ece5cc8dc
Create Date: 2019-05-07 15:36:22.709000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70dae4076c9c'
down_revision = '315ece5cc8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qrcode', sa.Column('name', sa.String(length=50), nullable=False))
    op.alter_column('qrcode', 'content',
               existing_type=sa.BLOB(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qrcode', 'content',
               existing_type=sa.BLOB(),
               nullable=True)
    op.drop_column('qrcode', 'name')
    # ### end Alembic commands ###
